SERIAL_DRIVER = vendor
AUDIO_DRIVER = pwm_hardware
POINTING_DEVICE_DRIVER = analog_joystick
DEFERRED_EXEC_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
AUDIO_ENABLE = yes
TAP_DANCE_ENABLE = yes